export const DEFAULT_SORRY_MESSAGES = [
  "Je suis vraiment desolee... Tu me pardonnes ?",
  "Allez, s'il te plait... je ferai tout ce que tu veux !",
  "Je t'offre un Delikatessen si tu me pardonnes ?",
  "OK, un resto gastronomique alors ?",
  "Je suis pret(e) a ramper s'il le faut...",
  "Tu sais que je t'adore, hein ? Pardon pardon pardon !",
  "Je te promets de ne plus jamais recommencer !",
  "Si tu me pardonnes, je fais la vaisselle pendant 1 mois.",
  "Je commence a avoir mal aux genoux a force de supplier...",
  "Tu veux que je chante ? Parce que je vais chanter.",
  "HELLO FROM THE OTHER SIIIIIIIIIIIIIIDE !!! PARDOOOOOON !",
  "Je t'envoie des ondes positives de pardon ~~~>",
  "Mon coeur est brise en 1000 morceaux. Non, 2000.",
  "Si tu dis oui, je te fais un gateau. Promis.",
  "Les scientifiques disent que pardonner rend plus heureux. C'est prouve !",
  "Meme Google dit qu'il faut me pardonner. Va verifier.",
  "C'est la 100eme fois que je demande... enfin presque.",
  "J'ai consulte un avocat, il dit que t'as pas le droit de pas pardonner.",
  "Je suis en train de battre le record mondial de demandes de pardon.",
  "Tu sais quoi ? Je t'aime meme si tu dis non. Mais dis oui quand meme.",
]

export const DEFAULT_SORRY_REFUSALS = [
  "Non ?! Mais... mais... OK je comprends... MAIS QUAND MEME !",
  "D'accord... *renifle*... je vais reessayer...",
  "Tu es DUR(E). Vraiment. Mais j'abandonne pas.",
  "Mon coeur vient de se fissurer un peu plus...",
  "C'est pas grave, j'ai tout mon temps. TOUT. MON. TEMPS.",
  "Meme les mechants dans les films pardonnent parfois !",
  "OK... je vais juste... rester la... et attendre...",
  "POURQUOIIIIII ?? *pleure en silence*",
  "Bon. Je vais monter d'un niveau alors.",
  "Tu sais que ce programme ne s'arrete JAMAIS, hein ?",
  "Ce bouton Non va bientot disparaitre... juste un avertissement.",
  "Meme si tu fermes la page, je serai la dans ton coeur.",
  "Je suis plus tenace qu'une tache de ketchup sur un t-shirt blanc.",
]
